springdoc:
  swagger-ui:
    path: /swagger-ui.html
    doc-expansion: none
    operations-sorter: alpha
    tags-sorter: alpha

spring:
  application:
    name: jpa
  jpa:
    show-sql: true
    properties:
      format_sql: true
      dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: validate
  jackson:
    time-zone: Asia/Seoul
  datasource:
    url: ${URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${NAME}
    password: ${PASSWORD}
  output:
    ansi:
      enabled: always

logging:
  level:
    org:
      apache:
        coyote:
          http11=trace: